AWSTemplateFormatVersion: "2010-09-09"
Description: "ECR with Policy For Area51 Account testing"
Parameters:
  environment:
    Type: String
    AllowedValues:
      - dev
      - qa
      - stag
  product:
    Type: String
    AllowedValues:
      - test
    Default: test
  service:
    Type: String
Resources:
  serviceEcr: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: ecr_test
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: 
              AWS: 
                - "arn:aws:iam::313686187887:root"
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"